In [56]:
import numpy as np
import pandas as pd

In [57]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [58]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters={}
    L=len(layer_dims)

    for l in range(1,L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l],1))

    return parameters

In [59]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [60]:
# checking the code 
layer_dims=[2,2,1]
for l in range(1,3):
    print(layer_dims[l-1])
    print(np.ones((layer_dims[l-1],layer_dims[l])))

2
[[1. 1.]
 [1. 1.]]
2
[[1.]
 [1.]]


In [61]:
def linear_forward(A_prev,w,b):
    z=np.dot(w.T,A_prev) + b
    return z

## forward propagation

In [62]:
def L_layer_forward(X,parameters):
    A=X
    L=len(parameters) // 2
    # print(L)
    for l in range(1,L+1):
        A_prev=A
        Wl=parameters['W'+ str(l)]
        bl=parameters['b' + str(l)]
        #print("A" + str(l-1) +": ",A_prev)
        #print('W'+str(l)+": ",Wl)
        #print('b'+str(l)+": ",bl)

        #print("--"*20)

        A=linear_forward(A_prev,Wl,bl)
        #print("A"+str(l)+": ",A)
        #print("**"*20)

    return A,A_prev

In [63]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1)     #shape (no of features ,no. of training example )
y=df[['lpa']].values[0][0].item()
X
y

4

In [64]:
parameters=initialize_parameters([2,2,1])
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [65]:
L_layer_forward(X,parameters)

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [66]:
len(parameters)

4

In [67]:
import numpy as np
W1= np.array([[0.1, 0.1],
        [0.1, 0.1]])
b1=np.array([[0.],
        [0.]])

In [68]:
X=np.array([[8],[8]])

In [69]:
np.dot(W1.T,X)

array([[1.6],
       [1.6]])

In [70]:
y_hat,A1=L_layer_forward(X,parameters)

In [71]:
y_hat=y_hat[0][0]

In [72]:
A1

array([[1.6],
       [1.6]])

In [73]:
def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0]=parameters['W2'][0][0] +(0.001 * 2*(y-y_hat)*A1[0][0])
    parameters['W2'][1][0]=parameters['W2'][1][0] +(0.001 * 2*(y-y_hat)*A1[1][0])
    parameters['b2'][0][0]=parameters['b2'][0][0] +(0.001 * 2*(y-y_hat))

    parameters['W1'][0][0]=parameters['W1'][0][0] +(0.001 * 2*(y-y_hat)*parameters['W1'][1][0]*X[0][0])
    parameters['W1'][0][1]=parameters['W1'][0][1] +(0.001 * 2*(y-y_hat)*parameters['W1'][0][1]*X[1][0])
    parameters['b1'][0][0]=parameters['b1'][0][0] +(0.001 * 2*(y-y_hat)*parameters['W1'][0][0])

    parameters['W1'][1][0]=parameters['W1'][1][0] +(0.001 * 2*(y-y_hat)*parameters['W1'][0][0]*X[0][0])
    parameters['W1'][1][1]=parameters['W1'][1][1] +(0.001 * 2*(y-y_hat)*parameters['W1'][0][1]*X[1][0])
    parameters['b1'][1][0]=parameters['b1'][1][0] +(0.001 * 2*(y-y_hat)*parameters['W1'][1][0])

In [74]:
update_parameters(parameters,y,y_hat,A1,X)

In [75]:
parameters

{'W1': array([[0.105888  , 0.105888  ],
        [0.10623469, 0.10623469]]),
 'b1': array([[0.00077934],
        [0.00078189]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

## epochs implementation

In [76]:
parameters=initialize_parameters([2,2,1])
epochs=5
for i in range(epochs):
    Loss=[]
    for j in range(df.shape[0]):
        X=df[['cgpa','profile_score']].values[j].reshape(2,1)
        y=df[['lpa']].values[j][0].item()

        y_hat,A1=L_layer_forward(X,parameters)
        y_hat=y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)
        Loss.append((y-y_hat)**2)
    print('Epoch-',i+1,'loss-',np.array(Loss).mean())


Epoch- 1 loss- 26.374350762258032
Epoch- 2 loss- 20.451628592038983
Epoch- 3 loss- 12.744126607486454
Epoch- 4 loss- 5.933011874264097
Epoch- 5 loss- 2.3315564093386536


In [77]:
parameters

{'W1': array([[0.22502414, 0.36028888],
        [0.22899114, 0.38164481]]),
 'b1': array([[0.02103924],
        [0.02137618]]),
 'W2': array([[0.43290287],
        [0.52809933]]),
 'b2': array([[0.13210712]])}

# Keras implementation

In [78]:
import pandas as pd
import numpy as np

In [79]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [80]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [81]:
model=Sequential()

In [82]:
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\Navneet\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [83]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [84]:
model.get_weights()

[array([[-0.8221563 ,  0.20955408],
        [ 0.8882526 , -0.066172  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.20950723],
        [0.06423318]], dtype=float32),
 array([0.], dtype=float32)]

In [85]:
# set new weight   --> custom weights 
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
            np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)
            ]

In [86]:
model.set_weights(new_weights)

In [87]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [88]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [89]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 27.8873
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.5883 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 27.2291
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.8882
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26.5544 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 26.1976
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 25.8411
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 25.4362
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 25.0628
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 24.6574
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 24.2305
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 23.7937
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 23.3889
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 22.9400
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 22.4446
Epoch 16/75
4/4 ━

In [90]:
model.get_weights()

[array([[0.37334034, 0.37334034],
        [0.36533955, 0.36533955]], dtype=float32),
 array([0.27204078, 0.27204078], dtype=float32),
 array([[0.37264216],
        [0.37264216]], dtype=float32),
 array([0.20464881], dtype=float32)]