In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','placed'])

In [4]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [19]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters={}
    L=len(layer_dims)
    for l in range(1,L):
        parameters['W'+str(l)]=np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b'+str(l)]=np.zeros((layer_dims[l],1))

    return parameters

In [20]:
# utility function
def sigmoid(Z):
    A=1/(1+np.exp(-Z))
    return A

In [21]:
def linear_forward(A_prev,W,b):
    Z=np.dot(W.T,A_prev) + b
    A=sigmoid(Z)
    return A

In [22]:
# L-layer feed forward
def L_layer_forward(X,parameters):
    A=X
    L=len(parameters)//2

    for l in range(1,L+1):
        A_prev=A
        W1=parameters['W'+str(l)]
        b1=parameters['b'+str(l)]


        A=linear_forward(A_prev,W1,b1)
    return A,A_prev
    

In [23]:
def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0]=parameters['W2'][0][0] + (0.0001*(y-y_hat)*A1[0][0])
    parameters['W2'][1][0]=parameters['W2'][1][0] + (0.0001*(y-y_hat)*A1[1][0])
    parameters['b2'][0][0]=parameters['b2'][0][0] + (0.0001*(y-y_hat))

    parameters['W1'][0][0]=parameters['W1'][0][0] + (0.0001*(y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
    parameters['W1'][0][1]=parameters['W1'][0][1] + (0.0001*(y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
    parameters['b1'][0][0]=parameters['b1'][0][0] + (0.0001*(y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

    parameters['W1'][1][0]=parameters['W1'][1][0] + (0.0001*(y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
    parameters['W1'][1][1]=parameters['W1'][1][1] + (0.0001*(y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
    parameters['b1'][1][0]=parameters['b1'][1][0] + (0.0001*(y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [24]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['placed']].values[0][0]

In [25]:
parameters=initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(X,parameters)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)

In [26]:
-y*np.log(y_hat)-(1-y)*np.log(1-y_hat)

np.float64(0.613402628898913)

In [27]:
parameters

{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[4.5849481e-05]])}

In [28]:
y_hat

np.float64(0.5415051895671072)

In [29]:
A1

array([[0.83201839],
       [0.83201839]])

#### epoch implementation

In [33]:
parameters=initialize_parameters([2,2,1])
epochs=100
for i in range(epochs):
    Loss=[]
    for j in range(df.shape[0]):
        X=df[['cgpa','profile_score']].values[j].reshape(2,1)
        y=df[['placed']].values[j][0].item()

        y_hat,A1=L_layer_forward(X,parameters)
        y_hat=y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)
        Loss.append((-y*np.log(y_hat)-(1-y)*np.log(1-y_hat)))
    print('Epoch-',i+1,'loss-',np.array(Loss).mean())

Epoch- 1 loss- 0.6939124309994983
Epoch- 2 loss- 0.6939114509742006
Epoch- 3 loss- 0.6939104713855384
Epoch- 4 loss- 0.6939094922333021
Epoch- 5 loss- 0.6939085135172819
Epoch- 6 loss- 0.6939075352372682
Epoch- 7 loss- 0.6939065573930516
Epoch- 8 loss- 0.6939055799844227
Epoch- 9 loss- 0.6939046030111722
Epoch- 10 loss- 0.693903626473091
Epoch- 11 loss- 0.6939026503699699
Epoch- 12 loss- 0.6939016747016002
Epoch- 13 loss- 0.6939006994677729
Epoch- 14 loss- 0.6938997246682792
Epoch- 15 loss- 0.6938987503029107
Epoch- 16 loss- 0.6938977763714584
Epoch- 17 loss- 0.6938968028737142
Epoch- 18 loss- 0.6938958298094697
Epoch- 19 loss- 0.6938948571785166
Epoch- 20 loss- 0.6938938849806471
Epoch- 21 loss- 0.6938929132156526
Epoch- 22 loss- 0.6938919418833256
Epoch- 23 loss- 0.693890970983458
Epoch- 24 loss- 0.6938900005158424
Epoch- 25 loss- 0.6938890304802711
Epoch- 26 loss- 0.6938880608765363
Epoch- 27 loss- 0.6938870917044309
Epoch- 28 loss- 0.6938861229637474
Epoch- 29 loss- 0.6938851546542

In [34]:
parameters

{'W1': array([[0.09998161, 0.09980799],
        [0.09998186, 0.0998081 ]]),
 'b1': array([[-5.25243134e-05],
        [-5.25178867e-05]]),
 'W2': array([[0.09921275],
        [0.09921293]]),
 'b2': array([[-0.00159669]])}

# keras Implementation

In [35]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [36]:
model=Sequential()

In [37]:
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

C:\Users\Navneet\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [38]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.get_weights()

[array([[ 0.9225973 , -0.50131565],
        [-0.5375452 ,  1.2123495 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.69913054],
        [-0.15216565]], dtype=float32),
 array([0.], dtype=float32)]

In [42]:
new_weights=[np.array([[0.1,0.1],
                      [0.1,0.1]],dtype=np.float32),
            np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)
            ]

In [43]:
model.set_weights(new_weights)

In [44]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [45]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [48]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.6944
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6942
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6938
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.6938
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6937
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6937
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6939
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.6938
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6939
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6936
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6937 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.6936
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.6936
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.6935
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6935
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━